# Generated by Django 4.2.4 on 2023-08-21 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=20)),
                ('restricao', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
