# Generated by Django 4.2.4 on 2023-08-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_venda_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='foto',
            field=models.FileField(blank=True, upload_to='fotos/'),
        ),
    ]
