# Generated by Django 4.2.4 on 2023-08-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_bike_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='foto',
            field=models.FileField(blank=True, upload_to='fotos'),
        ),
    ]
