# Generated by Django 4.2.4 on 2023-08-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_customuser_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
